kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistent-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pvm1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: persistent-storage-wp
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/pvm2"
